name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '11 13 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: tag and push image
        run: |
          docker build --push \
            --tag ghcr.io/davidmstraub/gramps-postgres:latest \
            --platform linux/amd64,linux/arm64 .
